dist: xenial

language: java

matrix:
  fast_finish: true
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
      env: _JAVA_OPTIONS=-Djdk.tls.client.protocols=TLSv1.2
    - jdk: openjdk12
    - jdk: openjdk-ea

  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk-ea
